# Page settings

# Page settings

baseURL = "/"
languageCode = "en-us"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ricardo Flores Camargo"
        tagline = "Físico"
        avatar = "ricardo.png"







    [params.contact]
        enable = true
        location = "Lima-Perú"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "986111117"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "r.flores@pucp.edu.pe"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://objective-heisenberg-273ce9.netlify.app/en/"
        text = "webfive"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python/R/Matlab"
        [[params.skills.list.items]]
        details = "Fortran/comsol multiphysics"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true
        
        [[params.education.list]]
        degree = "PhD Student in Physics"
        university = "Pontificia Universidad Católica del Perú"
        dates = "2019 - 2022"
        [[params.education.list]]
        degree = "Msc. Physics "
        university = "Universidad Nacional de Ingenieria"
        dates = "2017 - 2019"
        [[params.education.list]]
        degree = "Bsc Physics"
        university = "Universidad Nacional del Callao"
        dates = "2009 - 2015"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Spanish"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Study Physics at the National University of Callao. Work on quality control in ionizing radiation. In 2017 I won a scholarship by Concytec to study a Master's in Physics at the National University of Engineering. Investigate for two years on the application of hyperspectral camera in the near infrared to identify soils contaminated with petroleum hydrocarbons remotely and quickly. In the research work continuously with R and python programming languages and in the use of supervised and unsupervised models to create an algorithm applied to hyperspectral images. I am currently pursuing a PhD in physics at PUCP, my research topic analyzes time series with multivariate models and new models in the application of environmental ionizing radiation physics."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Researcher and practices monitor"
        dates = "2019 - Present"
        company = "PUCP"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Becado-Ayudante de investigación"
        dates = "2017 - 2019"
        company = "Universidad Nacional de Ingenieria"
        details = "Mi trabajo en la UNI ha estado enfocado principalmente en la implementación de un sistema para la adquisición de imágenes hiperespectrales para reconocer contaminantes de hidrocarburos en la superficie del suelo."
        [[params.experience.list.items]]
        details = "Adquisición de imagenes, limpieza de datos, pre-procesamient"
        [[params.experience.list.items]]
        details = "Estudios de diferentes métodos de procesamiento."

        [[params.experience.list]]
        title = "Laboratory analyst"
        dates = "2015 - 2017"
        company = "Aleph Grouph"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ricardoflorescamargo"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/ricardo-flores-camargo/"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/RicardoFloresC"
        title = "@username"





